In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
plt.style.use('seaborn')

In [2]:
from keras_preprocessing import image
import tensorflow.keras as keras

2023-06-08 10:06:38.852091: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-08 10:06:38.894388: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-08 10:06:39.261403: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-08 10:06:39.265794: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-08 10:06:40.421379: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Co

In [3]:
classes = os.listdir("./Train/")

train_data = []
train_labels = []

for pok in classes:
    folder = "./Train/" + pok
    for img_name in os.listdir(folder):
        img = image.load_img(f"{folder}/{img_name}", target_size= (100,100))
        img = image.img_to_array(img)
        train_data.append(img)
        train_labels.append(pok)

/usr/lib/python3/dist-packages/PIL/Image.py:945: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [4]:
test_data = []
test_labels = []

for pok in classes:
    folder = "./Test/" + pok
    for img_name in os.listdir(folder):
        img = image.load_img(f"{folder}/{img_name}", target_size= (100,100))
        img = image.img_to_array(img)
        test_data.append(img)
        test_labels.append(pok)

In [5]:
test_data = np.array(test_data)
test_labels = np.array(test_labels)
train_data = np.array(train_data)
train_labels = np.array(train_labels)
train_data.shape

(304, 100, 100, 3)

In [6]:
train_data = train_data.reshape(train_data.shape[0], 30000)
test_data = test_data.reshape(test_data.shape[0], 30000)

c2l = {"Pikachu" : 0, "Charmander" : 1, "Bulbasaur" : 2}
l2c = {0 : "Pikachu", 1: "Charmander", 2: "Bulbasaur"}

train_labels = np.array([c2l[i] for i in train_labels])
test_labels = np.array([c2l[i] for i in test_labels])
train_data.shape, train_labels.shape

((304, 30000), (304,))

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
train_labels = keras.utils.to_categorical(train_labels)

In [17]:
model = Sequential()
model.add(Dense(units=512, activation= 'relu', input_shape= (30000,)))
model.add(Dense(units=256, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=128, activation='relu'))
model.add(Dense(units=3, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [18]:
model.fit(train_data, train_labels, epochs= 25)

Epoch 1/25
10/10 [==============================] - 2s 118ms/step - loss: 2029.0740 - accuracy: 0.3026
Epoch 2/25
10/10 [==============================] - 1s 112ms/step - loss: 1214.9889 - accuracy: 0.4112
Epoch 3/25
10/10 [==============================] - 1s 107ms/step - loss: 1111.2223 - accuracy: 0.5132
Epoch 4/25
10/10 [==============================] - 1s 108ms/step - loss: 805.3185 - accuracy: 0.4737
Epoch 5/25
10/10 [==============================] - 1s 107ms/step - loss: 337.5449 - accuracy: 0.5132
Epoch 6/25
10/10 [==============================] - 1s 114ms/step - loss: 161.0901 - accuracy: 0.6382
Epoch 7/25
10/10 [==============================] - 1s 110ms/step - loss: 98.8569 - accuracy: 0.6809
Epoch 8/25
10/10 [==============================] - 1s 107ms/step - loss: 167.3001 - accuracy: 0.6151
Epoch 9/25
10/10 [==============================] - 1s 107ms/step - loss: 71.2338 - accuracy: 0.7204
Epoch 10/25
10/10 [==============================] - 1s 109ms/step - loss: 18.689

In [20]:
test_labels = keras.utils.to_categorical(test_labels)
test_labels

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [21]:
model.evaluate(test_data, test_labels)

4/4 [==============================] - 0s 13ms/step - loss: 10.0230 - accuracy: 0.9431


[10.022950172424316, 0.9430894255638123]

In [23]:
pred = model.predict(test_data).argmax(axis =1 )
pred

4/4 [==============================] - 0s 19ms/step


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [24]:
[l2c[i] for i in pred]

['Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Bulbasaur',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Charmander',
 'Pikachu',
 'Charmander',
 'Charmander',
 'Charmander',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasaur',
 'Bulbasau

In [28]:
test_img = "./Test/Pikachu/2010.jpg"
img = image.load_img(test_img, target_size=(100, 100))
img = image.img_to_array(img)
img = img.reshape(1, 30000)
img

array([[ 52., 141., 139., ...,  31.,  46.,  43.]], dtype=float32)

In [33]:
pred = model.predict(img).argmax(axis = 1)

1/1 [==============================] - 0s 39ms/step


In [38]:
l2c[pred[0]]

'Pikachu'

'Pikachu'

In [36]:
pred.shape

(1,)